### ISSUE TITLE
播放不了怎么回事

### ISSUE THREAD

**Issue by jaychou2012** [ksvc/ksplayer-web#1]
http://pl-ali.youku.com/playlist/m3u8?type=mp4&ts=1490185963&keyframe=0&vid=XMjYxOTQ1Mzg2MA==&ep=ciadGkiFU8cF4SvajD8bYyuwJiYHXJZ3rHbN%2FrYDAcZuH%2BrC6DPcqJ21TPs%3D&sid=04901859548541247bba8&token=0524&ctype=12&ev=1&oip=976319194

这个流地址无法播放

**Comment by chenjin3** [comment]
@jaychou2012   是因为这个流没有允许跨域访问。浏览器对跨域资源的访问有限制, 需要在服务端做配置允许浏览器跨域访问视频流或点播文件。 如果使用金山云服务,可以在ks3(对象存储)控制台对视频文件所在的存储空间进行设置。参见: CORS配置（https://docs.ksyun.com/read/latest/30/_book/service/cors.html） 。
